config/routes.rb
Rails.application.routes.draw do

  get 'faq' => 'pages#faq'

  get 'contact_us' => 'pages#contact'

  get 'legal' => 'pages#legal'

  get 'special_offers' => 'items#special'

  get 'terms_and_conditions' => 'pages#terms'

  # get 'items/index'
  #
  # get 'items/:id' => "items#show"
 resources :items

  ActiveAdmin.routes(self)
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :bids
  belongs_to :user

  # default_scope where('available_on < Time.now')


  # scope :new, order("created_at ASC")
  scope :active, -> { where('available_on < ?', Time.now)}
  scope :latest, -> { where('available_on < ?', Time.now).order("created_at ASC")}
  scope :expired, -> { where('closing_on < ?', Time.now)}
  # scope :expired, where("closing_on < Time.now" ).order("created_at ASC")
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :auctioneer, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :bids
  has_many :items

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def authenticate_admin_user!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "This area is restricted to administrators only."
      redirect_to root_path
    end
  end

  def current_admin_user
    return nil if user_signed_in? && !current_user.admin?
    current_user
  end

  def authorize_bid(item_id, amount)
    item = Item.find(item_id)
    if (item && amount > item.highest_bid.to_i)
      true
    else
      false
    end
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_filter :authenticate_user!

  def create
      if authorize_bid(create_bid_params[:item_id], create_bid_params[:amount])

      end
  end





  private

  def create_bid_params
    params.permit(:item_id, :amount)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
  end

  def destroy
  end

  def special

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def faq
  end

  def contact
  end

  def legal
  end

  def terms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @featured_items = Item.active.limit(4)
    @latest_items = Item.latest.limit(10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {featured_items: featured_items, latest_items: latest_items} }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/layouts/_footer.html.erb
<div id="footer-section">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12">
        <ul>
          <li>
            <h5>ACCOUNT</h5>
          </li>
          <li><a href="login.html">YOUR ACCOUNT</a></li>
          <li><a href="login.html">PERSONAL INFORMATION</a> </li>
          <li><a href="login.html">ADDRESSES</a> </li>
          <li><a href="login.html">DISCOUNT</a> </li>
          <li><a href="login.html">ORDER HISTORY</a></li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <ul>
          <li>
            <h5>INFORMATION</h5>
          </li>
          <li><%= link_to "CONTACT", contact_us_path %>  </li>
          <li><%= link_to "REGISTRATION", new_registration_path(:user) %> </li>
          <li><%= link_to "LEGAL NOTICE", legal_path %>  </li>
          <li><%= link_to "TERMS AND CONDITIONS", terms_and_conditions_path %> </li>
          <li><%= link_to "FAQ", faq_path %></li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <ul>
          <li>
            <h5>OUR OFFERS</h5>
          </li>
          <li><a href="#">NEW PRODUCTS</a> </li>
          <li><a href="#">TOP SELLERS</a>  </li>
          <li><a href="special_offer.html">SPECIAL OFFERS</a>  </li>
          <li><a href="#">MANUFACTURERS</a></li>
          <li><a href="#">SUPPLIERS</a> </li>
        </ul>
      </div>
      <div id="socialMedia" class="col-md-3 col-sm-6 col-xs-12 pull-right">
        <h5>SOCIAL MEDIA </h5>
        <%= link_to (image_tag "facebook.png", alt: "Facebook", title: "Facebook", style: "width:60px; height:60px"), root_path %>
        <%= link_to (image_tag "twitter.png", alt: "Twitter", title: "Twitter", style: "width:60px; height:60px"), root_path %>
        <!--<a href="#"><img width="60" height="60" src="themes/img/facebook.png" title="facebook" alt="facebook"/></a>-->
        <!--<a href="#"><img width="60" height="60" src="themes/img/twitter.png" title="twitter" alt="twitter"/></a>-->
        <!--<a href="#"><img width="60" height="60" src="themes/img/rss.png" title="rss" alt="rss"/></a>-->
        <!--<a href="#"><img width="60" height="60" src="themes/img/youtube.png" title="youtube" alt="youtube"/></a>-->
      </div>
    </div>
  </div>
  <!-- Container End -->
</div>
<div id="bottom-line">
  <div class="container">
    <p class="pull-right">&copy; Bellspot</p>
    <p> All rights Reserved <a href="tac.html">Terms</a> <a href="legal_notice.html">Legal notice</a></p>
  </div>
</div>
<!-- Placed at the end of the document so the pages load faster ============================================= -->
<!--<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>-->
<!--<script src="themes/js/bootstrap.min.js" type="text/javascript"></script>-->
<!--<script src="themes/js/custom.js" type="text/javascript"></script>-->
<!-- <script src="themes/js/jquery.lightbox-0.5.js"></script> -->
<script type="text/javascript">
    $('#myCarousel').carousel({
        interval: 7000
    })
    $('#featured').carousel({
        interval: 4000
    })
    $(function() {
        $('#gallery a').lightBox();
    });
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header id="header">
  <div class="container">
    <div class="hidden-xs hidden-sm">
      <div id="welcome-line" class="row">
        <div class="col-md-6 col-sm-6 col-xs-12 welcome"><%= current_user  ? "Welcome! #{current_user.name}" : "Welcome to Bellspot!" %> </div>
        <div class="col-md-6 col-sm-6 col-xs-12  hidden-xs">
          <div class="pull-right">
            <!-- Split button -->
            <div class="btn-group">
              <button type="button" class="btn ">En </button>
              <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">En</a></li>
                <!--<li><a href="#">Fr</a></li>-->
                <!--<li><a href="#">Es</a></li>-->
                <!--<li><a href="#">De</a></li>-->
              </ul>
            </div>
            <!-- Split button -->
            <div class="btn-group">
              <button type="button" class="btn dropdown-toggle">&#36; 1200.00</button>
              <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">&euro; 882.03</a></li>
                <li><a href="#">&pound; 716.16</a></li>
              </ul>
            </div>
            <div class="btn-group">
              <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-shopping-cart"></i> Your recent bids[ 4 ]  <span class="caret"></span></button>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <ul class="media-list">
                    <li class="media item1">
                      <%= link_to (image_tag "products/10.jpg", alt: "#", class: "media-object"), root_path, class: "pull-left" %>
                      <div class="media-body">
                        <h4 class="media-heading">Camera</h4>
                        <p><strong>$220.00</strong></p>
                      </div>
                      <a class="remove-me" href="#"><i class="fa fa-trash-o"></i> remove</a>
                    </li>
                    <li class="media item1">
                      <%= link_to (image_tag "products/9.jpg", alt: "#", class: "media-object"), root_path, class: "pull-left" %>

                      <div class="media-body">
                        <h4 class="media-heading">Camera</h4>
                        <p><strong>$400.00</strong></p>
                      </div>
                      <a class="remove-me" href="#"><i class="fa fa-trash-o"></i> remove</a>
                    </li>
                    <li class="media item1">
                      <%= link_to (image_tag "products/8.jpg", alt: "#", class: "media-object"), "#", class: "pull-left" %>

                      <div class="media-body">
                        <h4 class="media-heading">Classic Camera</h4>
                        <p><strong>$500.00</strong></p>
                      </div>
                      <a class="remove-me" href="#"><i class="fa fa-trash-o"></i> remove</a>
                    </li>
                    <li class="media item1">
                      <%= link_to (image_tag "products/7.jpg", alt: "#", class: "media-object"), "#", class: "pull-left" %>

                      <div class="media-body">
                        <h4 class="media-heading">Lens</h4>
                        <p><strong>$80.00</strong></p>
                      </div>
                      <a class="remove-me" href="#"><i class="fa fa-trash-o"></i> remove</a>
                    </li>
                    <li class="cntr">
                      <a class="btn btn-danger block" href="product_summary.html">$1200.00  Checkout </a>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#sidebar" style="float: left">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to (image_tag "logo.png", alt: "Bellspot", class: "media-object"), "/", class: "navbar-brand logo hidden-xs" %>
        <%= link_to (image_tag "logo.png", alt: "Bellspot", class: "media-object"), "/", class: "navbar-brand logo mlogo hidden-md hidden-lg hidden-sm" %>

      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation">
        <form class="hidden-sm" role="search">
          <div class="col-md-4 col-sm-6 col-xs-12">
            <input id="srchFld" type="text" class="form-control" placeholder="I'm looking for ...">
          </div>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Special Offers", special_offers_path %></li>
          <li><%= link_to "Items", items_path %> </li>
          <li class="hidden-xs"><%= link_to "Contact", contact_us_path %></li>
          <li class="hidden-md hidden-sm hidden-lg"><%= link_to "Login", new_user_session_path %></li>
          <!--<li class="hidden-md hidden-sm hidden-lg"><a href="product_summary.html">Checkout [$1200.00]</a></li>-->
          <li class="dropdown hidden-xs">
            <% if !user_signed_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Login <b class="caret"></b></a>
                <% else %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.name %> <b class="caret"></b></a>
                <% end %>
                <ul id="dropped-menu" class="dropdown-menu " role="menu">
              <li>

                <% if user_signed_in? %>


                  <li>
                    <%= link_to(main_app.user_path(current_user)) do %>
                        <i class="icon-user"></i> Profile

                    <% end %>
                  </li>

                  <li>
                    <%= link_to(main_app.edit_user_registration_path) do %>
                        <i class="icon-cog"></i> Preferences

                    <% end %>
                  </li>

                  <li>
                    <%= link_to("#") do %>
                        <i class="icon-envelope visible-desktop"></i> Contact Support

                    <% end %>
                  </li>

                  <li class="divider"></li>

                  <li>
                    <%= link_to(main_app.destroy_user_session_path, :method => 'delete') do %>
                        <i class="icon-off"></i> Sign Out

                    <% end %>
                  </li>




              <% else %>



              <%= form_for(:user, :url => main_app.user_session_path(:next => request.path), html: { class: "form-horizontal", role: "form" } ) do |f| %>

              <!--<form class="form-horizontal" role="form">-->
                  <div class="form-group">
                    <div class="col-sm-12">
                      <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
                      <!--<input type="email" class="form-control" placeholder="Email">-->
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-12">
                      <%= f.password_field :password, placeholder: "Password", class: "form-control" %>

                      <!--<input type="password" class="form-control" placeholder="Password">-->
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-12">
                      <div class="checkbox">
                        <label>
                          <input id="user_remember_me" type="checkbox" value="1" name="user[remember_me]"> Remember me
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-12">
                      <%= link_to "Forgot Password?", new_password_path('user'), class: "pull-right" %>

                      <%= f.submit 'Sign in', :id => "submit", class: "btn tbn-danger" %>
                    </div>
                  </div>
                <!--</form>-->
                    <% end %>
                    <% end %>
</ul>
              </li>
            </ul>
          </li>

        </ul>
      </nav>
    </div>


  </div>
</header>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bellspot" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bellspot" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/contact.html.erb
<div class="container">
  <div class="row">
    <div id="sidebar" class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <ul id="sideManu" class="list-group">
        <li class="subMenu list-group-item open">
          <a class="active"> <i class="fa fa-angle-right"></i>  ELECTRONICS [235]</a>
          <ul>
            <li><a href="products.html"> Cameras (100) <i class="fa fa-angle-right pull-right"></i> </a></li>
            <li><a href="products.html"> Computers, Tablets & laptop (30) <i class="fa fa-angle-right pull-right"></i></a></li>
            <li><a href="products.html"> Mobile Phone (80) <i class="fa fa-angle-right pull-right"></i></a></li>
            <li><a href="products.html"> Sound & Vision (15) <i class="fa fa-angle-right pull-right"></i></a></li>
          </ul>
        </li>
        <li class="subMenu list-group-item">
          <a class=""> <i class="fa fa-angle-right"></i> CLOTHES [840] </a>
          <ul style="display:none">
            <li><a href="products.html">  Women's Clothing (45)<i class="fa fa-angle-right pull-right"></i></a></li>
            <li><a href="products.html">  Women's Shoes (8) <i class="fa fa-angle-right pull-right"></i></a></li>
            <li><a href="products.html">  Women's Hand Bags (5) <i class="fa fa-angle-right pull-right"></i></a></li>
            <li><a href="products.html">  Men's Clothings  (45) <i class="fa fa-angle-right pull-right"></i></a></li>
            <li><a href="products.html">  Men's Shoes (6) <i class="fa fa-angle-right pull-right"></i></a></li>
            <li><a href="products.html">  Kids Clothing (5)<i class="fa fa-angle-right pull-right"></i></a></li>
            <li><a href="products.html">  Kids Shoes (3)<i class="fa fa-angle-right pull-right"></i></a></li>
          </ul>
        </li>
        <li class="subMenu list-group-item">
          <a>  <i class="fa fa-angle-right"></i> FOOD AND BEVERAGES [1000]</a>
          <ul style="display:none">
            <li><a href="products.html">  Angoves  (35)</a></li>
            <li><a href="products.html">  Bouchard Aine & Fils (8)</a></li>
            <li><a href="products.html">  French Rabbit (5)</a></li>
            <li><a href="products.html">  Louis Bernard  (45)</a></li>
            <li><a href="products.html">  BIB Wine (Bag in Box) (8)</a></li>
            <li><a href="products.html">  Other Liquors & Wine (5)</a></li>
            <li><a href="products.html">  Garden (3)</a></li>
            <li><a href="products.html">  Khao Shong (11)</a></li>
          </ul>
        </li>
        <li class="subMenu list-group-item"><a href="products.html"> <i class="fa fa-angle-right"></i> HEALTH & BEAUTY [18]</a></li>
        <li class="subMenu list-group-item"><a href="products.html"> <i class="fa fa-angle-right"></i> SPORTS & LEISURE [58]</a></li>
        <li class="subMenu list-group-item"><a href="products.html"> <i class="fa fa-angle-right"></i> BOOKS & ENTERTAINMENTS [14]</a></li>
      </ul>
      <div class="hidden-xs">
        <div id="specialOffer" class="carousel slide" data-ride="carousel">
          <!-- Wrapper for slides -->
          <h3 class="cntr">Special Offer</h3>
          <div class="carousel-inner">
            <div class="item active">
              <div class="thumbnail">
                <a href="product_details.html"><img src="themes/img/products/16gb-memory.jpg" alt=""></a>
                <div class="caption">
                  <h5 class="cntr">8GB Memory Card</h5>
                  <h4><a class="btn btn-success" href="product_details.html">VIEW <span>$2.00</span></a></h4>
                </div>
              </div>
            </div>
            <div class="item">
              <div class="thumbnail">
                <a href="product_details.html"><img src="themes/img/products/8gb-memory.jpg" alt=""></a>
                <div class="caption">
                  <h5 class="cntr">16GB Memory Card</h5>
                  <h4><a class="btn btn-success" href="product_details.html">VIEW <span>$1.50</span></a></h4>
                </div>
              </div>
            </div>
          </div>
        </div>
        <h3 class="cntr">Coming Soon</h3>
        <div class="thumbnail">
          <a href="product_details.html"><img src="themes/img/products/new-kindle.jpg" title="Bootshop New Kindel" alt="Bootshop Kindel"></a>
          <div class="caption">
            <h5 class="cntr">Kindle</h5>
          </div>
        </div>
        <h4>We Accepts</h4>
        <img src="themes/img/payment_methods.png" title="Bootshop Payment Methods" alt="Payments Methods"/>
      </div>
    </div>
    <div id="main-col" class="col-lg-9 col-md-8 col-sm-8 col-xs-12">
      <ul class="breadcrumb">
        <li><a href="index.html">Home</a> <span class="divider"> </span></li>
        <li class="active">Contact</li>
      </ul>
      <h1>Contact Us</h1>
      <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
          <h3> Leave A Message </h3>
          <p class="body_paragraph contact-paragraph">
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
          </p>
          <form role="form" method="post" class="form-wrapper">
            <div class="form-group">
              <div class="row">
                <div class="col-xs-7">
                  <label for="name">
                    Name *
                  </label>
                  <input type="text" required="" placeholder="Your Name" minlength="2" data-errmsg="Name is required." class="form-control" name="name" id="name">
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-xs-7">
                  <label for="email">
                    Email *
                  </label>
                  <input type="text" required="" placeholder="Your Email" minlength="2" data-errmsg="Email is required." class="form-control" name="email" id="email">
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-xs-7">
                  <label for="message">
                    Subject
                  </label>
                  <input type="text" placeholder="Your Subject" class="form-control" name="subject" id="subject">
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-xs-8">
                  <label for="message&quot;">
                    Message *
                  </label>
                  <textarea required="" rows="3" placeholder="Your Message" data-errmsg="Message is required." class="form-control" name="message" id="message"></textarea>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-2 col-sm-2 offset2">
                <input type="submit" class="btn btn-danger btn-lg" value="Submit Message">
              </div>
            </div>
          </form>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 col-md-offset-1 col-lg-offset-1">
          <h3>Contact Details</h3>
          <p>
            <span><i class="fa fa-phone"></i> (+44) 111-222-333</span><br/>
            <span><i class="fa fa-envelope"></i> email@domain.com</span><br/>
            <span><i class="fa fa-home"></i> Address, Post Code, Country</span><br/>
          </p>
          <br/>
          <br/>
          <h3> MARKETING DEPARTMENT </h3>
          <p>
            <span><i class="fa fa-phone"></i> (+44) 111-222-333</span><br/>
            <span><i class="fa fa-envelope"></i> email@domain.com</span><br/>
            <span><i class="fa fa-home"></i> Address, Post Code, Country</span><br/>
          </p>
          <br/>
          <br/>
          <h3> SALES DEPARTMENT </h3>
          <p>
            <span><i class="fa fa-phone"></i> (+44) 111-222-333</span><br/>
            <span><i class="fa fa-envelope"></i> email@domain.com</span><br/>
            <span><i class="fa fa-home"></i> Address, Post Code, Country</span><br/>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_coming_soon.html.erb
<h3 class="cntr">Coming Soon</h3>
<div class="thumbnail">
  <%= link_to (image_tag "products/new-kindle.jpg", alt: "Kindle"), root_path %>
  <div class="caption">
    <h5 class="cntr">Kindle</h5>
  </div>
</div>

app/views/shared/_item_medium.html.erb
<div class="col-md-4 col-sm-6 col-xs-12">
<div class="thumbnail">
  <div class="product-overlay">
    <a href="/"><img alt="#" src="/assets/products/5.jpg"></a>
    <div class="share-addto-cart">
      <a class="btn btn-default" href="#"><i class="fa fa-share-alt"></i></a> <br><br>
      <a class="btn btn-default" href="#"><i class="fa fa-heart"></i></a> <br><br>
      <a class="btn btn-danger" href="#"><i class="fa fa-comment-o"></i></a>
    </div>
  </div>
  <div class="caption">
    <h5> <%= item_medium.name %> </h5>
    <p>
      <%= item_medium.tagline %>
    </p>
    <p> <%= link_to "BID",item_medium, class:"btn btn-success pull-left"  %> <span class="pull-right price">$222.00</span></p>
  </div>
</div>
</div>

app/views/shared/_we_accept.html.erb
<h4>We Accept</h4>
<%= link_to (image_tag "payment_methods.png", alt: "Payments Methods", title: "Bellspot Payment Methods" ), root_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>